# Use Ubuntu 14.04
dist: trusty

sudo: required

language: ruby

rvm: 2.2.3

cache:
  - apt: true
  - bundler: true
  - directories:
    - $HOME/.ivy2/cache

jdk:
  - oraclejdk8

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/texlive-2017
  - sudo apt-get update
  - sudo apt-get full-upgrade -f texlive-full
  - sudo apt-get install -y fonts-lmodern

install:
  - gem install nanoc:4.0.2
  - gem install redcarpet
  - gem install nokogiri
  - wget https://github.com/jgm/pandoc/releases/download/2.0.5/pandoc-2.0.5-1-amd64.deb && sudo dpkg -i pandoc-2.0.5-1-amd64.deb

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
      - key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt=1.0.0
      - latex-cjk-all
      - texlive-full

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M"

script:
  - /usr/bin/sbt scalafmtTest scripted makeSite
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - .travis/publish-site.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/ghpages
    - $HOME/.sbt/boot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
